name = "cf-url-shortener"
type = "webpack"

account_id = "d7c39ce11b3d2ece25f80f52709d02f1"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-25"

# [secrets]
# Do not use plaintext environment variables to store sensitive information. Use `wrangler secret put` instead.
# UPSTASH_REDIS_REST_URL
# UPSTASH_REDIS_REST_TOKEN
# UPSTASH_KAFKA_REST_URL
# UPSTASH_KAFKA_REST_USERNAME
# UPSTASH_KAFKA_REST_PASSWORD
